### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#1]
## Overview

1. Write code for **Binary Search in C++.**
2. Add that code into a directory named "**Searching**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by sambhavgupta0705** [comment]
Hey Can I work on this issue?

**Comment by Prajwal0225** [comment]
Hey! @sambhavgupta0705 are you still working on it?  If not then I would love to work on this issue.

**Comment by sambhavgupta0705** [comment]
I am working on it

**Comment by Prajwal0225** [comment]
Okk 😊.

**Comment by Prajwal0225** [comment]
@vashuteotia123 Thanks for assigning me this issue

**Comment by Mani628** [comment]
can you assign this to me ?? I am ready with the code

**Comment by utkarshsingx** [comment]
can you assign this to me please. I would work on this issue

**Comment by kanishkasrivastava** [comment]
#174 please merge my code as i have tried to help you
