### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#10]
## Overview

1. Write code for **Merge Sort in C++.**
2. Add that code into a directory named "**Sorting**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by RAYANI630** [comment]
Can I work on this issue?

**Comment by aashishxetri5** [comment]
Hey @RAYANI630, are you working on this? If not I'd like to work on this.

**Comment by RAYANI630** [comment]
@aashishxetri5 I'm working on it.

**Comment by muskaanrajput14** [comment]
Can I work on this issue??
