### ISSUE TITLE
Linear Searching

### ISSUE THREAD

**Issue by ShivanshDengla** [VishER-hacktoberfest/Cpp-Algos#102]
Hey, I can write the code for linear search in c++. Do assign me this issue if you accept it
Thanks

**Comment by muskaanrajput14** [comment]
Please assign this task to me

**Comment by ShivanshDengla** [comment]
Sorry, i shouldnt have added the issue, i guess its not allowed.
I though we can suggest our own codes problems but didnt knew it would add it in the issue tab.
I am a little new to github so please forgive for this mistake.
Thank You
