### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#11]
## Overview

1. Write code for **Quick Sort in C++.**
2. Add that code into a directory named "**Sorting**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by RockingRishav** [comment]
I want to work upon this issue

**Comment by KumarUtsav1025** [comment]
Sir, I want to work on this. Can you please assign it to me.

**Comment by vashuteotia123** [comment]
> Sir, I want to work on this. Can you please assign it to me.
> 

The issue has already been assigned.
PTAL on other issues.
