### ISSUE TITLE
Segment Tree

### ISSUE THREAD

**Issue by Sumedh-byte** [VishER-hacktoberfest/Cpp-Algos#126]
**Overview**

1. Write code for #Segment Tree in C++.

1. Add that code into a directory named "Tree", if the directory doesn't exist, create one and add the code file.

Please take care of these things while creating the pull request.

- The code file was added to the correct directory.

- Code quality looks good.

- The programming language used is the same as mentioned in the issue.

**Comment by sohamdata** [comment]
Hi, could you please assign this issue to me? @vashuteotia123

**Comment by Siddharthqr** [comment]
Hi, Can I work on this issue? @vashuteotia123

**Comment by sohamdata** [comment]
My submission wasn't merged with main, kindly look into it and mark it as
hacktober accepted
