### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#14]
## Overview

1. Write code for **Bubble Sort in C++.**
2. Add that code into a directory named "**Sorting**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by sambhavgupta0705** [comment]
Hey can I work on this issue?

**Comment by sambhavgupta0705** [comment]
Thank you for assigning me this issue.

**Comment by sdhanraj300** [comment]
Can I work on it?

**Comment by muskaanrajput14** [comment]
Please assign this task to me

**Comment by sdhanraj300** [comment]
I made a pulll request please check it
