### ISSUE TITLE
Comb Sort

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#17]
## Overview

1. Write code for **Comb Sort in C++.**
2. Add that code into a directory named "**Sorting**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by semi-infiknight** [comment]
please assign me this issue

**Comment by r-o-n-i-t** [comment]
I can contribute here. Consider assigning me to this issue. 
Thanks.
@vashuteotia123
