### ISSUE TITLE
Cycle Sort

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#19]
## Overview

1. Write code for **Cycle Sort in C++.**
2. Add that code into a directory named "**Sorting**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by semi-infiknight** [comment]
please assign me this issue

**Comment by omkarvw** [comment]
Hello there, could you please assign this issue to me ?
