### ISSUE TITLE
Linear Search

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#2]
## Overview

1. Write code for **Linear Search in C++.**
2. Add that code into a directory named "**Searching**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by Nisarg-Chokshi** [comment]
@vashuteotia123 Can I work on this ?

**Comment by aashishxetri5** [comment]
Hey @Nisarg-Chokshi , are you working on this issue? If not, I'd like to work on this.

**Comment by ananya-1112** [comment]
I would like to work on this
