### ISSUE TITLE
Kruskal's Algorithm

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#20]
## Overview

1. Write code for **Kruskal's Algorithm in C++.**
2. Add that code into a directory named "**Graphs**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by sarthak17jain** [comment]
Please assign me this issue.

**Comment by vashuteotia123** [comment]
> Can I work on this issue??

Hey @muskaanrajput14,
This issue has already been assigned.
