### ISSUE TITLE
Dijkstra's Algorithm 

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#21]
## Overview

1. Write code for **Dijkstra's Algorithm  in C++.**
2. Add that code into a directory named "**Graphs**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by saimaheshtaduri** [comment]
I can contribute here. consider assigning me to this issue.  Thanks. @vashuteotia123

**Comment by r-o-n-i-t** [comment]
Hello, I'm a participant in Hacktoberfest 2022. I want to contribute to this issue. 
Thank you,
@vashuteotia123

**Comment by vashuteotia123** [comment]
> Hello, I'm a participant in Hacktoberfest 2022. I want to contribute to this issue. 
> Thank you,
> @vashuteotia123 
> 

This issue is already been assigned.
