### ISSUE TITLE
Bellman Ford Algorithm 

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#22]
## Overview

1. Write code for **Bellman Ford Algorithm  in C++.**
2. Add that code into a directory named "**Graphs**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by semi-infiknight** [comment]
please assign me this issue

**Comment by kataranandini** [comment]
please assign this to me i can do this

**Comment by Mihir-63** [comment]
Can I work on this?
