### ISSUE TITLE
Flood Fill Algorithm

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#25]
## Overview

1. Write code for **Flood Fill Algorithm in C++.**
2. Add that code into a directory named "**Graphs**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by omkarvw** [comment]
Hello, I am new to open source and would like to learn more about it. So could you please assign it to me.

**Comment by Sumercode** [comment]
Hey, I can contribute the complete C++ code , with comments 
The whole code will be neat and self explanatory
Please assign me this , Thanks !

**Comment by omkarvw** [comment]
I have already made a pull request for the above issue.

**Comment by omkarvw** [comment]
Hello, how do we link a pull request to the issue assigned to us. I have already made a pull request for above issue.
