### ISSUE TITLE
Prim's Algorithm

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#27]
## Overview

1. Write code for **Prim's Algorithm in C++.**
2. Add that code into a directory named "**Graphs**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by sambhavgupta0705** [comment]
hey I can add this algorithm .

**Comment by vashuteotia123** [comment]
> hey I can add this algorithm .

Hey @sambhavgupta0705,

Yes you can, but remember if you are looking for a hacktoberfest contribution. It will only be counted if made on or after 1st October.

**Comment by jatin-code21** [comment]
please assign this task to me. I am ready to contribute it

**Comment by Siddharthqr** [comment]
Assign it to me, if not done.
