### ISSUE TITLE
Boruvka's Algorithm 

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#28]
## Overview

1. Write code for **Boruvka's Algorithm in C++.**
2. Add that code into a directory named "**Graphs**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by yaegareren** [comment]
Hey,  I'd like to contribute the code for this algorithm. Please assign it to me.

**Comment by As-anonymus** [comment]
If nobody is working on this can you assign it to me ?

**Comment by yaegareren** [comment]
@vashuteotia123 I have completed the code and made a pr for the same. Kindly review it.
