### ISSUE TITLE
Johnson's Algorithm 

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#29]
## Overview

1. Write code for **Johnson's Algorithm in C++.**
2. Add that code into a directory named "**Graphs**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by ShivanshDengla** [comment]
Hey,
i am new on opensource and came here from the youtube video, can i try to work on this issue?

**Comment by vashuteotia123** [comment]
> Hey,
> i am new on opensource and came here from the youtube video, can i try to work on this issue?

Yes, now you can.

**Comment by ShivanshDengla** [comment]
> > Hey,
> > i am new on opensource and came here from the youtube video, can i try to work on this issue?
> 
> Yes, now you can.

hey i made a pull request, i don't know if i did it right. If theres any problem please let me know. Thank you

**Comment by ShivanshDengla** [comment]
#77
