### ISSUE TITLE
Depth First Search

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#3]
## Overview

1. Write code for **Depth First Search in C++.**
2. Add that code into a directory named "**Searching**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by RockingRishav** [comment]
I want to work upon this issue please assign it to me.

**Comment by Sudhanshu-Purohit** [comment]
i want to work on this issue i will do it with proper comments, time and space complexity also.
