### ISSUE TITLE
Kosaraju's Algorithm

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#30]
## Overview

1. Write code for **Kosaraju's Algorithm in C++.**
2. Add that code into a directory named "**Graphs**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by Arnav-Negi** [comment]
Hi I can work on this, please assign it to me.

**Comment by Arnav-Negi** [comment]
I have written the code. I will create a PR after 1st October because of Hacktoberfest.

**Comment by Arnav-Negi** [comment]
Pull request created, kindly look into it
