### ISSUE TITLE
Kadane's Algorithm 

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#32]
## Overview

1. Write code for **Kadane's Algorithm in C++.**
2. Add that code into a directory named "**Arrays**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by sambhavgupta0705** [comment]
Hey I can work on this  issue

**Comment by kataranandini** [comment]
Hey,Is it still open . Can i Work on it?

**Comment by muskaanrajput14** [comment]
is it open ?? I want to work on it please tell me

**Comment by vashuteotia123** [comment]
Hey @kataranandini & @muskaanrajput14,

This issue has already been assigned, PTAL on other issues.
