### ISSUE TITLE
Floyd's Cycle Detection Algorithm 

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#33]
## Overview

1. Write code for **Floyd's Cycle Detection Algorithm in C++.**
2. Add that code into a directory named "**Arrays**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by RAYANI630** [comment]
Can you assign this to me?

**Comment by muskaanrajput14** [comment]
Please assign this task to me
