### ISSUE TITLE
Boyer - More Majority Vote Algorithm 

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#36]
## Overview

1. Write code for **Boyer - More Majority Vote Algorithm in C++.**
2. Add that code into a directory named "**Arrays**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by semi-infiknight** [comment]
Please assign me this issue

**Comment by Ravnoor12** [comment]
Please assign me this issue

**Comment by Siddharthqr** [comment]
Please assign me this issue
