### ISSUE TITLE
Binary Indexed Tree or Fenwick Tree

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#38]
## Overview

1. Write code for **Binary Indexed Tree or Fenwick Tree in C++.**
2. Add that code into a directory named "**Tree**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by Arnav-Negi** [comment]
Hey I want to work on this, assign it to me if possible.

**Comment by Arnav-Negi** [comment]
I have written the code. I will create a PR after 1st October because of Hacktoberfest.

**Comment by ShivanshDengla** [comment]
Hey,
I have made a Pull Request #101 for this code. You can check it out, if theres some issue you can let me know.
Thanks

**Comment by Arnav-Negi** [comment]
Pull request created, kindly looking into it
