### ISSUE TITLE
Breadth First Search

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#4]
## Overview

1. Write code for **Breadth First Search in C++.**
2. Add that code into a directory named "**Searching**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by saimaheshtaduri** [comment]
I can work on this issue. assign to me if possible. @vashuteotia123

**Comment by Sumedh-byte** [comment]
Hey, can I work on this issue?

**Comment by hd2342-dubey** [comment]
Hello, I want to work over this, please assign it to me if.
