### ISSUE TITLE
Cartesian Tree 

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#40]
## Overview

1. Write code for **Cartesian Tree in C++.**
2. Add that code into a directory named "**Tree**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by manish831** [comment]
@vashuteotia123  sir, plz do assign it to me.

**Comment by As-anonymus** [comment]
Sir i have already submitted for pull request , pl look into it  for mergng

**Comment by As-anonymus** [comment]
Can you merge the request
