### ISSUE TITLE
Interval Tree  

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#42]
## Overview

1. Write code for **Interval Tree in C++.**
2. Add that code into a directory named "**Tree**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by muskaanrajput14** [comment]
I want to work on this task, please assign it to me

**Comment by priyankaaa532002** [comment]
Hey @vashuteotia123, Can you assign me this issue? I would love to work on it.
