### ISSUE TITLE
Finger Tree 

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#43]
## Overview

1. Write code for **Finger Tree in C++.**
2. Add that code into a directory named "**Tree**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by manish831** [comment]
@vashuteotia123  plz assign it to me.

**Comment by Siddharthqr** [comment]
Can this issue be assigned to me??

**Comment by Satorusimpp** [comment]
can you please assign this issue to me?

**Comment by rachana2522** [comment]
Can you please assign it to me?

**Comment by saty-a** [comment]
can you please assign it to me!
