### ISSUE TITLE
Scapegoat Tree 

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#45]
## Overview

1. Write code for **Scapegoat Tree in C++.**
2. Add that code into a directory named "**Tree**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by omkarvw** [comment]
Hello Sir, could you please assign this issue to me ?
Thank You.

**Comment by ShivanshDengla** [comment]
Hey,
Can i write the code for this?

**Comment by ShivanshDengla** [comment]
hey i made a pull request #89 Do let me know if its good, i can make changes if required
Thanks
