### ISSUE TITLE
Rabin-Karp Algorithm

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#5]
## Overview

1. Write code for **Rabin-Karp Algorithm in C++.**
2. Add that code into a directory named "**Searching**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by Nisarg-Chokshi** [comment]
@vashuteotia123 Can I work on this ?

**Comment by adarshgupta404** [comment]
Can i work on this issue?
