### ISSUE TITLE
Z Algorithm

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#6]
## Overview

1. Write code for **Z Algorithm in C++.**
2. Add that code into a directory named "**Searching**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by omkarvw** [comment]
Hello there, could you please assign this issue to me ?

**Comment by priyankaaa532002** [comment]
Hey @vashuteotia123, Can you assign me this issue? I would love to work on it.
