### ISSUE TITLE
Heap Sort

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#8]
## Overview

1. Write code for **Heap Sort in C++.**
2. Add that code into a directory named "**Sorting**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by semi-infiknight** [comment]
please assign me this issue

**Comment by akshitsangwan** [comment]
Hey @vashuteotia123, I am interested to contribute to this task. Can you please assign me this issue?

**Comment by akshitsangwan** [comment]
Hey @vashuteotia123, I have raised the PR for this issue. Kindly review my PR and please merge the same if you find it appropriate. Please provide your valuable feedback:)

**Comment by akshitsangwan** [comment]
#62
