### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by vashuteotia123** [VishER-hacktoberfest/Cpp-Algos#9]
## Overview

1. Write code for **Selection Sort in C++.**
2. Add that code into a directory named "**Sorting**", if the directory doesn't exist, create one and add the code file.

#### Please take care of these things while creating the pull request.

- The code file was added to the correct directory. 
- Code quality looks good.
- The programming language used is the same as mentioned in the issue.

**Comment by sambhavgupta0705** [comment]
Hey Can I work on this issue?

**Comment by muskaanrajput14** [comment]
can i work on this ???

**Comment by manish831** [comment]
I had done work on it.
Plz check #103
